# Generated by Django 5.2 on 2025-04-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(db_column='adminID', primary_key=True, serialize=False)),
                ('tc', models.CharField(max_length=11, unique=True)),
                ('sifre', models.TextField()),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArastirmaProjeleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje_turu', models.TextField()),
                ('proje_detaylari', models.TextField(blank=True, null=True)),
                ('proje_belgesi', models.TextField(blank=True, null=True)),
                ('gorev_belgesi', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arastirma_projeleri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atiflar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atif_turu', models.TextField()),
                ('eserin_adi_ve_atis_sayisi', models.TextField(blank=True, null=True)),
                ('pdf_yolu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atiflar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BilimselToplantiFaaliyetleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilimsel_toplanti_turu', models.TextField()),
                ('detaylar', models.TextField(blank=True, null=True)),
                ('belge_yolu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bilimsel_toplanti_faaliyetleri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Editorluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.TextField()),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('gorev_belge', models.TextField(blank=True, null=True)),
                ('indeks_belge', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'editorluk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EgitimFaaliyetleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_turu', models.TextField()),
                ('ders_detaylari', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'egitim_faaliyetleri',
                 'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GuzelSanatlarFaaliyetleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faaliyet_turu', models.TextField()),
                ('detaylar', models.TextField(blank=True, null=True)),
                ('dokuman', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guzel_sanatlar_faaliyetleri',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdariGorevler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev_turu', models.TextField()),
                ('gorev_birimi_yili', models.TextField(blank=True, null=True)),
                ('belge_yukle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'idari_gorevler',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JuriAdaylari',
            fields=[
                ('juriid', models.AutoField(db_column='juriID', primary_key=True, serialize=False)),
                ('isim', models.TextField()),
                ('soyisim', models.TextField()),
                ('unvan', models.TextField()),
                ('kullanici_rolu', models.TextField()),
                ('tc', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'db_table': 'juri_adaylari',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JuriDegerlendirme',
            fields=[
                ('juridegerlendirmeid', models.AutoField(db_column='juriDegerlendirmeID', primary_key=True, serialize=False)),
                ('juri_raporu', models.TextField(blank=True, null=True)),
                ('onay_durumu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'juri_degerlendirme',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KisiselBilgiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_soyad', models.TextField(db_column='ad_soyad')),
                ('tc_kimlik_no', models.CharField(db_column='tc_kimlik_no', max_length=11)),
                ('dogum_tarihi', models.DateField(blank=True, db_column='dogum_tarihi', null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('adres', models.TextField(blank=True, db_column='adres', null=True)),
                ('kadro_turu', models.CharField(blank=True, choices=[('PROFESOR', 'Profesör'), ('DOCENT', 'Doçent'), ('DOKTOR', 'Doktor'), ('OGRETIM_GOREVLISI', 'Öğretim Görevlisi'), ('ARASTIRMA_GOREVLISI', 'Araştırma Görevlisi')], db_column='akademik_unvan', max_length=20, null=True)),
            ],
            options={
                'db_table': 'kisisel_bilgiler',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kitaplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitap_turu', models.TextField()),
                ('kitap_detaylari', models.TextField(blank=True, null=True)),
                ('kapak_ve_icindekiler_pdf', models.TextField(blank=True, null=True)),
                ('yayin_taninirlik_pdf', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kitaplar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Makaleler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_turu', models.TextField()),
                ('yazarlar_dergi_bilgi', models.TextField(blank=True, null=True)),
                ('pdf_yolu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'makaleler',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oduller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.TextField()),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('belge_pdf', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oduller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patentler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_turu', models.TextField()),
                ('patent_detaylari', models.TextField()),
                ('patent_belgesi_pdf', models.TextField()),
            ],
            options={
                'db_table': 'patentler',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TezYoneticilikleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tez_turu', models.TextField()),
                ('tez_detaylari', models.TextField()),
                ('tez_belgesi_pdf', models.TextField()),
            ],
            options={
                'db_table': 'tez_yoneticilikleri',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Yonetici',
            fields=[
                ('yonetici_id', models.AutoField(primary_key=True, serialize=False)),
                ('isim', models.TextField()),
                ('soyisim', models.TextField()),
                ('tc', models.CharField(max_length=11, unique=True)),
                ('sifre', models.TextField()),
                ('unvan', models.TextField()),
                ('rol', models.TextField()),
            ],
            options={
                'db_table': 'yonetici',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('ilanID', models.AutoField(primary_key=True, serialize=False)),
                ('bolum', models.TextField()),
                ('pozisyon', models.TextField()),
                ('aciklama', models.TextField()),
                ('bilgilendirme_dosya', models.BinaryField(blank=True, null=True)),
                ('basl_tarih', models.DateField()),
                ('bitis_tarih', models.DateField()),
                ('kadro_sayi', models.IntegerField()),
                ('basvuru_sayisi', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ilan',
            },
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tc_kimlik_no', models.CharField(max_length=11, unique=True)),
                ('ad_soyad', models.TextField()),
                ('sifre_hash', models.TextField(default='password123')),
                ('rol', models.CharField(max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('son_giris', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kullanicilar',
            },
        ),
        migrations.CreateModel(
            name='Basvurular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('faaliyet_donemi', models.TextField(blank=True, null=True)),
                ('basvurulan_kadro', models.TextField()),
                ('basvuru_aciklam', models.TextField(blank=True, null=True)),
                ('basvuru_tarihi', models.DateField()),
                ('arastirma_projesi', models.ForeignKey(blank=True, db_column='arastirma_projeleri_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_arastirma', to='core.arastirmaprojeleri')),
                ('atif', models.ForeignKey(blank=True, db_column='atiflar_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_atif', to='core.atiflar')),
                ('bilimsel_toplanti', models.ForeignKey(blank=True, db_column='bilimsel_toplanti_faaliyetleri_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_toplanti', to='core.bilimseltoplantifaaliyetleri')),
                ('editorluk', models.ForeignKey(blank=True, db_column='editorluk_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_editorluk', to='core.editorluk')),
                ('egitim_faaliyet', models.ForeignKey(blank=True, db_column='egitim_faaliyetleri_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_egitim', to='core.egitimfaaliyetleri')),
                ('guzel_sanat', models.ForeignKey(blank=True, db_column='guzel_sanatlar_faaliyetleri_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_guzel_sanat', to='core.guzelsanatlarfaaliyetleri')),
                ('idari_gorev', models.ForeignKey(blank=True, db_column='idari_gorevler_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_idari', to='core.idarigorevler')),
                ('kisisel_bilgi', models.ForeignKey(blank=True, db_column='kisisel_bilgi_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kisiselbilgiler')),
                ('kitap', models.ForeignKey(blank=True, db_column='kitaplar_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_kitap', to='core.kitaplar')),
                ('makale', models.ForeignKey(blank=True, db_column='makaleler_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_makale', to='core.makaleler')),
                ('odul', models.ForeignKey(blank=True, db_column='oduller_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_odul', to='core.oduller')),
                ('patent', models.ForeignKey(blank=True, db_column='patentler_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_patent', to='core.patentler')),
                ('tez_yoneticilik', models.ForeignKey(blank=True, db_column='tez_yoneticilikleri_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basvuru_tez_yoneticilikleri', to='core.tezyoneticilikleri')),
                ('ilan', models.ForeignKey(blank=True, db_column='ilan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ilan')),
                ('kullanici', models.ForeignKey(db_column='kullanici_id', on_delete=django.db.models.deletion.CASCADE, to='core.kullanici')),
            ],
            options={
                'db_table': 'basvurular',
            },
        ),
    ]
