# Generated by Django 5.2 on 2025-04-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='editorluk',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='egitimfaaliyetleri',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='guzelsanatlarfaaliyetleri',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='idarigorevler',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='juriadaylari',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='juridegerlendirme',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='kisiselbilgiler',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='kitaplar',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='makaleler',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='oduller',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patentler',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tezyoneticilikleri',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='yonetici',
            options={'managed': False},
        ),
    ]
