# Generated by Django 5.2 on 2025-04-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_djangosession_options_alter_editorluk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvurular',
            name='basvuru_pdf',
            field=models.BinaryField(blank=True, null=True, verbose_name='Başvuru Onay PDF’i'),
        ),
    ]
