# Generated by Django 5.2 on 2025-04-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guzelsanatlarfaaliyeti_kitap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atif',
            name='basvuru',
        ),
        migrations.DeleteModel(
            name='ArastirmaProjeleri',
        ),
        migrations.DeleteModel(
            name='BilimselToplantiFaaliyetleri',
        ),
        migrations.DeleteModel(
            name='EgitimFaaliyetleri',
        ),
        migrations.DeleteModel(
            name='IdariGorevler',
        ),
        migrations.DeleteModel(
            name='Makaleler',
        ),
        migrations.DeleteModel(
            name='Oduller',
        ),
        migrations.DeleteModel(
            name='Patentler',
        ),
        migrations.DeleteModel(
            name='TezYoneticilikleri',
        ),
        migrations.AlterModelOptions(
            name='arastirmaprojesi',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='basvuru',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bilimseltoplantifaaliyeti',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='egitimfaaliyeti',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='idarigorev',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ilan',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='kullanici',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='makale',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='odul',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tezyonetciligi',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Atif',
        ),
    ]
