# Generated by Django 5.2 on 2025-04-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_atif_basvuru_delete_arastirmaprojeleri_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tezyonetciligi',
            table='tez_yoneticilikleri',
        ),
    ]
