# Generated by Django 5.2 on 2025-04-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tezyonetciligi_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kisiselbilgiler',
            options={'managed': False, 'verbose_name': 'Kişisel Bilgi', 'verbose_name_plural': 'Kişisel Bilgiler'},
        ),
    ]
