# Generated by Django 5.2 on 2025-04-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_kisiselbilgiler_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basvuru',
            options={'managed': True},
        ),
    ]
